package com.project.back_end.models;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;

import jakarta.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

// @Entity annotation:
//    - Marks the class as a JPA entity, which means it represents a table in the database.
//    - It is required for persistence frameworks like Hibernate to map the class to a database table.
@Entity
public class Admin {

    // 1. 'id' field:
    //    - Type: private Long
    //    - Description: 
    //      - Represents the unique identifier for the Admin entity.
    //      - This field is auto-generated by the database using @GeneratedValue with strategy GenerationType.IDENTITY.
    //      - It is the primary key of the entity, identified by @Id annotation.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // 3. 'password' field:
    //    - Type: private String
    //    - Description: 
    //      - Represents the password of the admin for authentication.
    //      - The field is marked with @JsonProperty(access = JsonProperty.Access.WRITE_ONLY) to prevent the password from being exposed in JSON responses.
    //      - @NotNull validation ensures the password cannot be null when creating or updating an Admin.
    @NotNull(message = "password cannot be null")
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private String password;

    // 4. 'email' field:
    //    - Type: private String
    //    - Description:
    //      - Represents the email address of the admin.
    //      - Used for login/authentication in place of username if needed.
    //      - Optional field (can add @NotNull if required).
    @NotNull(message = "email cannot be null")
    private String email;

    // 5. Constructor(s):
    //    - A no-argument constructor is implicitly provided, required by JPA for entity creation.
    //    - A parameterized constructor can be added as needed.
    public Admin() {}

    public Admin(String email, String password) {
        this.email = email;
        this.password = password;
    }

    // 6. Getters and Setters:
    //    - Standard getter and setter methods are provided for accessing and modifying the fields.
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    // Getter e Setter per la nuova email
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
}